// Copyright (c) 2025 Lucinda. All rights reserved.
// Licensed under the MIT License.

using Lucinda.Blazor.Interop;

namespace Lucinda.Blazor.Protocol.X3DH;

/// <summary>
/// Provides X3DH (Extended Triple Diffie-Hellman) key agreement operations for Blazor WebAssembly.
/// </summary>
/// <remarks>
/// <para>
/// X3DH establishes a shared secret between two parties using:
/// <list type="bullet">
/// <item><description>Identity Keys: Long-term identity key pairs</description></item>
/// <item><description>Signed Pre-Keys: Medium-term pre-keys signed by identity key</description></item>
/// <item><description>One-Time Pre-Keys: Ephemeral keys for additional forward secrecy</description></item>
/// <item><description>Ephemeral Keys: Session-specific keys generated by initiator</description></item>
/// </list>
/// </para>
/// <para>
/// The shared secret is derived from 3 or 4 ECDH computations:
/// <code>
/// DH1 = DH(IK_A, SPK_B)     - Sender Identity + Recipient Signed Pre-Key
/// DH2 = DH(EK_A, IK_B)      - Sender Ephemeral + Recipient Identity
/// DH3 = DH(EK_A, SPK_B)     - Sender Ephemeral + Recipient Signed Pre-Key
/// DH4 = DH(EK_A, OPK_B)     - Sender Ephemeral + Recipient One-Time Pre-Key (optional)
/// 
/// SK = KDF(DH1 || DH2 || DH3 || DH4)
/// </code>
/// </para>
/// </remarks>
public sealed class BlazorX3DHKeyAgreement : IAsyncDisposable
{
    private readonly WebCryptoInterop _cryptoInterop;
    private readonly string _curve;
    private readonly string _hashAlgorithm;
    private bool _disposed;

    /// <summary>
    /// The info parameter for HKDF key derivation in X3DH.
    /// </summary>
    private static readonly byte[] X3DHInfo = System.Text.Encoding.UTF8.GetBytes("X3DH");

    /// <summary>
    /// Initializes a new instance of the <see cref="BlazorX3DHKeyAgreement"/> class.
    /// </summary>
    /// <param name="cryptoInterop">The Web Crypto interop service.</param>
    /// <param name="curve">The elliptic curve to use. Default is P-256.</param>
    /// <param name="hashAlgorithm">The hash algorithm for HKDF. Default is SHA-256.</param>
    public BlazorX3DHKeyAgreement(
        WebCryptoInterop cryptoInterop,
        string curve = "P-256",
        string hashAlgorithm = "SHA-256")
    {
        _cryptoInterop = cryptoInterop ?? throw new ArgumentNullException(nameof(cryptoInterop));
        _curve = curve;
        _hashAlgorithm = hashAlgorithm;
    }

    /// <summary>
    /// Gets the algorithm name.
    /// </summary>
    public string AlgorithmName => $"X3DH-{_curve}";

    /// <summary>
    /// Performs X3DH key agreement as the initiator (Alice).
    /// </summary>
    /// <param name="senderIdentityKeyPair">The sender's identity key pair.</param>
    /// <param name="recipientBundle">The recipient's pre-key bundle.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The X3DH result containing the shared secret and associated data.</returns>
    public async Task<BlazorX3DHResult> InitiatorAgreeAsync(
        BlazorAsymmetricKeyPair senderIdentityKeyPair,
        BlazorPreKeyBundle recipientBundle,
        CancellationToken cancellationToken = default)
    {
        ThrowIfDisposed();
        ArgumentNullException.ThrowIfNull(senderIdentityKeyPair);
        ArgumentNullException.ThrowIfNull(recipientBundle);

        // Verify the signed pre-key signature
        bool isValid = await _cryptoInterop.EcdsaVerifyAsync(
            recipientBundle.IdentityKey,
            recipientBundle.SignedPreKey,
            recipientBundle.SignedPreKeySignature,
            _curve,
            _hashAlgorithm);

        if (!isValid)
        {
            throw new InvalidOperationException("Signed pre-key signature is invalid.");
        }

        cancellationToken.ThrowIfCancellationRequested();

        // Generate ephemeral key pair
        (byte[]? ephemeralPublicKey, byte[]? ephemeralPrivateKey) = await _cryptoInterop.GenerateEcdhKeyPairAsync(_curve);
        cancellationToken.ThrowIfCancellationRequested();

        try
        {
            // Perform the DH computations
            List<byte[]> dhResults = [];

            // DH1: Sender Identity (private) + Recipient Signed Pre-Key (public)
            byte[] dh1 = await _cryptoInterop.EcdhDeriveBitsAsync(
                senderIdentityKeyPair.PrivateKey,
                recipientBundle.SignedPreKey,
                _curve);
            dhResults.Add(dh1);
            cancellationToken.ThrowIfCancellationRequested();

            // DH2: Sender Ephemeral (private) + Recipient Identity (public)
            byte[] dh2 = await _cryptoInterop.EcdhDeriveBitsAsync(
                ephemeralPrivateKey,
                recipientBundle.IdentityKey,
                _curve);
            dhResults.Add(dh2);
            cancellationToken.ThrowIfCancellationRequested();

            // DH3: Sender Ephemeral (private) + Recipient Signed Pre-Key (public)
            byte[] dh3 = await _cryptoInterop.EcdhDeriveBitsAsync(
                ephemeralPrivateKey,
                recipientBundle.SignedPreKey,
                _curve);
            dhResults.Add(dh3);
            cancellationToken.ThrowIfCancellationRequested();

            // DH4: Sender Ephemeral (private) + Recipient One-Time Pre-Key (public) - optional
            int? usedOneTimePreKeyId = null;
            if (recipientBundle.HasOneTimePreKey)
            {
                byte[] dh4 = await _cryptoInterop.EcdhDeriveBitsAsync(
                    ephemeralPrivateKey,
                    recipientBundle.OneTimePreKey!,
                    _curve);
                dhResults.Add(dh4);
                usedOneTimePreKeyId = recipientBundle.OneTimePreKeyId;
                cancellationToken.ThrowIfCancellationRequested();
            }

            // Concatenate all DH outputs
            byte[] dhConcat = ConcatenateArrays(dhResults.ToArray());

            // Derive the shared secret using HKDF
            byte[] sharedSecret = await _cryptoInterop.HkdfDeriveKeyAsync(
                dhConcat,
                [], // No salt
                X3DHInfo,
                32, // 256 bits
                _hashAlgorithm);

            // Create associated data (AD = Encode(IK_A) || Encode(IK_B))
            byte[] associatedData = ConcatenateArrays(
                senderIdentityKeyPair.PublicKey,
                recipientBundle.IdentityKey);

            // Clear sensitive data
            Array.Clear(dhConcat, 0, dhConcat.Length);
            foreach (byte[] dh in dhResults)
            {
                Array.Clear(dh, 0, dh.Length);
            }

            return new BlazorX3DHResult(
                sharedSecret,
                associatedData,
                ephemeralPublicKey,
                usedOneTimePreKeyId);
        }
        finally
        {
            // Clear ephemeral private key
            Array.Clear(ephemeralPrivateKey, 0, ephemeralPrivateKey.Length);
        }
    }

    /// <summary>
    /// Performs X3DH key agreement as the responder (Bob).
    /// </summary>
    /// <param name="recipientIdentityKeyPair">The recipient's identity key pair.</param>
    /// <param name="recipientSignedPreKeyPair">The recipient's signed pre-key pair.</param>
    /// <param name="recipientOneTimePreKeyPair">The recipient's one-time pre-key pair (optional).</param>
    /// <param name="senderIdentityPublicKey">The sender's identity public key.</param>
    /// <param name="senderEphemeralPublicKey">The sender's ephemeral public key.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The X3DH result containing the shared secret and associated data.</returns>
    public async Task<BlazorX3DHResult> ResponderAgreeAsync(
        BlazorAsymmetricKeyPair recipientIdentityKeyPair,
        BlazorAsymmetricKeyPair recipientSignedPreKeyPair,
        BlazorAsymmetricKeyPair? recipientOneTimePreKeyPair,
        byte[] senderIdentityPublicKey,
        byte[] senderEphemeralPublicKey,
        CancellationToken cancellationToken = default)
    {
        ThrowIfDisposed();
        ArgumentNullException.ThrowIfNull(recipientIdentityKeyPair);
        ArgumentNullException.ThrowIfNull(recipientSignedPreKeyPair);
        ArgumentNullException.ThrowIfNull(senderIdentityPublicKey);
        ArgumentNullException.ThrowIfNull(senderEphemeralPublicKey);

        // Perform the DH computations (mirror of initiator)
        List<byte[]> dhResults = [];

        // DH1: Recipient Signed Pre-Key (private) + Sender Identity (public)
        byte[] dh1 = await _cryptoInterop.EcdhDeriveBitsAsync(
            recipientSignedPreKeyPair.PrivateKey,
            senderIdentityPublicKey,
            _curve);
        dhResults.Add(dh1);
        cancellationToken.ThrowIfCancellationRequested();

        // DH2: Recipient Identity (private) + Sender Ephemeral (public)
        byte[] dh2 = await _cryptoInterop.EcdhDeriveBitsAsync(
            recipientIdentityKeyPair.PrivateKey,
            senderEphemeralPublicKey,
            _curve);
        dhResults.Add(dh2);
        cancellationToken.ThrowIfCancellationRequested();

        // DH3: Recipient Signed Pre-Key (private) + Sender Ephemeral (public)
        byte[] dh3 = await _cryptoInterop.EcdhDeriveBitsAsync(
            recipientSignedPreKeyPair.PrivateKey,
            senderEphemeralPublicKey,
            _curve);
        dhResults.Add(dh3);
        cancellationToken.ThrowIfCancellationRequested();

        // DH4: Recipient One-Time Pre-Key (private) + Sender Ephemeral (public) - optional
        if (recipientOneTimePreKeyPair != null)
        {
            byte[] dh4 = await _cryptoInterop.EcdhDeriveBitsAsync(
                recipientOneTimePreKeyPair.PrivateKey,
                senderEphemeralPublicKey,
                _curve);
            dhResults.Add(dh4);
            cancellationToken.ThrowIfCancellationRequested();
        }

        // Concatenate all DH outputs
        byte[] dhConcat = ConcatenateArrays(dhResults.ToArray());

        // Derive the shared secret using HKDF
        byte[] sharedSecret = await _cryptoInterop.HkdfDeriveKeyAsync(
            dhConcat,
            [], // No salt
            X3DHInfo,
            32, // 256 bits
            _hashAlgorithm);

        // Create associated data (AD = Encode(IK_A) || Encode(IK_B))
        byte[] associatedData = ConcatenateArrays(
            senderIdentityPublicKey,
            recipientIdentityKeyPair.PublicKey);

        // Clear sensitive data
        Array.Clear(dhConcat, 0, dhConcat.Length);
        foreach (byte[] dh in dhResults)
        {
            Array.Clear(dh, 0, dh.Length);
        }

        return new BlazorX3DHResult(
            sharedSecret,
            associatedData,
            null, // Responder doesn't return ephemeral public key
            null);
    }

    /// <summary>
    /// Generates a complete pre-key bundle with private keys.
    /// </summary>
    /// <param name="identityKeyPair">The identity key pair.</param>
    /// <param name="signedPreKeyId">The ID for the signed pre-key.</param>
    /// <param name="oneTimePreKeyIds">Optional array of IDs for one-time pre-keys.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The pre-key bundle with private keys.</returns>
    public async Task<BlazorPreKeyBundleWithPrivateKeys> GeneratePreKeyBundleAsync(
        BlazorAsymmetricKeyPair identityKeyPair,
        int signedPreKeyId,
        int[]? oneTimePreKeyIds = null,
        CancellationToken cancellationToken = default)
    {
        ThrowIfDisposed();
        ArgumentNullException.ThrowIfNull(identityKeyPair);

        // Generate signed pre-key
        (byte[]? signedPreKeyPublic, byte[]? signedPreKeyPrivate) = await _cryptoInterop.GenerateEcdhKeyPairAsync(_curve);
        cancellationToken.ThrowIfCancellationRequested();

        // Sign the signed pre-key with identity key
        // Note: We need to use ECDSA key pair for signing. For simplicity, we'll generate a separate signing key
        // In a real implementation, identity keys should be ECDSA keys or have dual-purpose
        (byte[]? signingPublic, byte[]? signingPrivate) = await _cryptoInterop.GenerateEcdsaKeyPairAsync(_curve);
        cancellationToken.ThrowIfCancellationRequested();

        byte[] signature = await _cryptoInterop.EcdsaSignAsync(
            signingPrivate,
            signedPreKeyPublic,
            _curve,
            _hashAlgorithm);
        cancellationToken.ThrowIfCancellationRequested();

        // Generate one-time pre-keys
        Dictionary<int, byte[]> oneTimePreKeyPrivates = [];
        byte[]? firstOneTimePreKeyPublic = null;
        int? firstOneTimePreKeyId = null;

        if (oneTimePreKeyIds != null && oneTimePreKeyIds.Length > 0)
        {
            for (int i = 0; i < oneTimePreKeyIds.Length; i++)
            {
                (byte[]? opkPublic, byte[]? opkPrivate) = await _cryptoInterop.GenerateEcdhKeyPairAsync(_curve);
                oneTimePreKeyPrivates[oneTimePreKeyIds[i]] = opkPrivate;

                if (i == 0)
                {
                    firstOneTimePreKeyPublic = opkPublic;
                    firstOneTimePreKeyId = oneTimePreKeyIds[i];
                }
                cancellationToken.ThrowIfCancellationRequested();
            }
        }

        // Create the public bundle
        BlazorPreKeyBundle bundle = new(
            signingPublic, // Using signing public key as identity key
            signedPreKeyPublic,
            signature,
            signedPreKeyId,
            firstOneTimePreKeyPublic,
            firstOneTimePreKeyId);

        return new BlazorPreKeyBundleWithPrivateKeys(
            bundle,
            signingPrivate,
            signedPreKeyPrivate,
            oneTimePreKeyPrivates);
    }

    /// <summary>
    /// Generates a new identity key pair.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A new identity key pair.</returns>
    public async Task<BlazorAsymmetricKeyPair> GenerateIdentityKeyPairAsync(
        CancellationToken cancellationToken = default)
    {
        ThrowIfDisposed();
        (byte[]? publicKey, byte[]? privateKey) = await _cryptoInterop.GenerateEcdsaKeyPairAsync(_curve);
        return new BlazorAsymmetricKeyPair(publicKey, privateKey);
    }

    /// <summary>
    /// Generates a new ECDH key pair.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A new ECDH key pair.</returns>
    public async Task<BlazorAsymmetricKeyPair> GenerateEphemeralKeyPairAsync(
        CancellationToken cancellationToken = default)
    {
        ThrowIfDisposed();
        (byte[]? publicKey, byte[]? privateKey) = await _cryptoInterop.GenerateEcdhKeyPairAsync(_curve);
        return new BlazorAsymmetricKeyPair(publicKey, privateKey);
    }

    private static byte[] ConcatenateArrays(params byte[][] arrays)
    {
        int totalLength = 0;
        foreach (byte[] arr in arrays)
        {
            totalLength += arr.Length;
        }

        byte[] result = new byte[totalLength];
        int offset = 0;
        foreach (byte[] arr in arrays)
        {
            Buffer.BlockCopy(arr, 0, result, offset, arr.Length);
            offset += arr.Length;
        }

        return result;
    }

    /// <inheritdoc/>
    public async ValueTask DisposeAsync()
    {
        if (_disposed)
        {
            return;
        }

        _disposed = true;
        await ValueTask.CompletedTask;
    }

    private void ThrowIfDisposed()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
    }
}
