// <copyright file="X3DHKeyAgreement.cs" company="Lucinda">
// Copyright (c) Lucinda. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

#if NET6_0_OR_GREATER
using System.Security.Cryptography;

using Lucinda.Abstractions;
using Lucinda.KeyDerivation;
using Lucinda.KeyExchange;
using Lucinda.Signatures;
using Lucinda.Utilities;

namespace Lucinda.Protocol.X3DH
{
    /// <summary>
    /// Provides X3DH (Extended Triple Diffie-Hellman) key agreement operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// X3DH establishes a shared secret between two parties using:
    /// <list type="bullet">
    /// <item><description>Identity Keys: Long-term identity key pairs</description></item>
    /// <item><description>Signed Pre-Keys: Medium-term pre-keys signed by identity key</description></item>
    /// <item><description>One-Time Pre-Keys: Ephemeral keys for additional forward secrecy</description></item>
    /// <item><description>Ephemeral Keys: Session-specific keys generated by initiator</description></item>
    /// </list>
    /// </para>
    /// <para>
    /// The shared secret is derived from 3 or 4 ECDH computations:
    /// <code>
    /// DH1 = DH(IK_A, SPK_B)     - Sender Identity + Recipient Signed Pre-Key
    /// DH2 = DH(EK_A, IK_B)      - Sender Ephemeral + Recipient Identity
    /// DH3 = DH(EK_A, SPK_B)     - Sender Ephemeral + Recipient Signed Pre-Key
    /// DH4 = DH(EK_A, OPK_B)     - Sender Ephemeral + Recipient One-Time Pre-Key (optional)
    /// 
    /// SK = KDF(DH1 || DH2 || DH3 || DH4)
    /// </code>
    /// </para>
    /// </remarks>
    public sealed class X3DHKeyAgreement : IX3DHKeyAgreement, IDisposable
    {
        private readonly ECCurve _curve;
        private readonly HkdfKeyDerivation _hkdf;
        private bool _disposed;

        /// <summary>
        /// The info parameter for HKDF key derivation in X3DH.
        /// </summary>
        private static readonly byte[] X3DHInfo = "X3DH"u8.ToArray();

        /// <summary>
        /// Initializes a new instance of the <see cref="X3DHKeyAgreement"/> class.
        /// </summary>
        /// <param name="curve">The elliptic curve to use. Default is P-256.</param>
        public X3DHKeyAgreement(ECCurve? curve = null)
        {
            _curve = curve ?? ECCurve.NamedCurves.nistP256;
            _hkdf = new HkdfKeyDerivation(HashAlgorithmName.SHA256);
        }

        /// <inheritdoc/>
        public string AlgorithmName => $"X3DH-{GetCurveName(_curve)}";

        /// <inheritdoc/>
        public CryptoResult<X3DHResult> InitiatorAgree(
            AsymmetricKeyPair senderIdentityKeyPair,
            PreKeyBundle recipientBundle)
        {
            ThrowIfDisposed();

            if (senderIdentityKeyPair == null)
            {
                return CryptoResult<X3DHResult>.Failure("Sender identity key pair cannot be null.");
            }

            if (recipientBundle == null)
            {
                return CryptoResult<X3DHResult>.Failure("Recipient bundle cannot be null.");
            }

            try
            {
                // Verify the signed pre-key signature
                CryptoResult<bool> verifyResult = VerifySignedPreKey(
                    recipientBundle.IdentityKey,
                    recipientBundle.SignedPreKey,
                    recipientBundle.SignedPreKeySignature);

                if (verifyResult.IsFailure)
                {
                    return CryptoResult<X3DHResult>.Failure($"Signature verification failed: {verifyResult.Error}");
                }

                if (!verifyResult.Value)
                {
                    return CryptoResult<X3DHResult>.Failure("Signed pre-key signature is invalid.");
                }

                // Generate ephemeral key pair
                using EcdhKeyExchange ephemeralEcdh = new(_curve);
                CryptoResult<AsymmetricKeyPair> ephemeralResult = ephemeralEcdh.GenerateKeyPair();
                if (ephemeralResult.IsFailure)
                {
                    return CryptoResult<X3DHResult>.Failure($"Failed to generate ephemeral key: {ephemeralResult.Error}");
                }

                byte[] ephemeralPublicKey = ephemeralResult.Value.PublicKey;
                byte[] ephemeralPrivateKey = ephemeralResult.Value.PrivateKey;

                // Perform the DH computations
                List<byte[]> dhResults = new();

                // DH1: Sender Identity (private) + Recipient Signed Pre-Key (public)
                CryptoResult<byte[]> dh1 = PerformDH(senderIdentityKeyPair.PrivateKey, recipientBundle.SignedPreKey);
                if (dh1.IsFailure)
                {
                    return CryptoResult<X3DHResult>.Failure($"DH1 failed: {dh1.Error}");
                }
                dhResults.Add(dh1.Value);

                // DH2: Sender Ephemeral (private) + Recipient Identity (public)
                CryptoResult<byte[]> dh2 = PerformDH(ephemeralPrivateKey, recipientBundle.IdentityKey);
                if (dh2.IsFailure)
                {
                    return CryptoResult<X3DHResult>.Failure($"DH2 failed: {dh2.Error}");
                }
                dhResults.Add(dh2.Value);

                // DH3: Sender Ephemeral (private) + Recipient Signed Pre-Key (public)
                CryptoResult<byte[]> dh3 = PerformDH(ephemeralPrivateKey, recipientBundle.SignedPreKey);
                if (dh3.IsFailure)
                {
                    return CryptoResult<X3DHResult>.Failure($"DH3 failed: {dh3.Error}");
                }
                dhResults.Add(dh3.Value);

                // DH4: Sender Ephemeral (private) + Recipient One-Time Pre-Key (public) - optional
                int? usedOneTimePreKeyId = null;
                if (recipientBundle.HasOneTimePreKey)
                {
                    CryptoResult<byte[]> dh4 = PerformDH(ephemeralPrivateKey, recipientBundle.OneTimePreKey!);
                    if (dh4.IsFailure)
                    {
                        return CryptoResult<X3DHResult>.Failure($"DH4 failed: {dh4.Error}");
                    }
                    dhResults.Add(dh4.Value);
                    usedOneTimePreKeyId = recipientBundle.OneTimePreKeyId;
                }

                // Concatenate all DH outputs
                byte[] dhConcat = ConcatenateArrays(dhResults.ToArray());

                // Derive the shared secret using HKDF
                CryptoResult<byte[]> sharedSecretResult = _hkdf.DeriveKey(dhConcat, null, X3DHInfo, 32);
                if (sharedSecretResult.IsFailure)
                {
                    return CryptoResult<X3DHResult>.Failure($"Key derivation failed: {sharedSecretResult.Error}");
                }

                // Create associated data (AD = Encode(IK_A) || Encode(IK_B))
                byte[] associatedData = ConcatenateArrays(
                    senderIdentityKeyPair.PublicKey,
                    recipientBundle.IdentityKey);

                // Clear sensitive data
                CryptoHelpers.SecureClear(dhConcat);
                foreach (byte[] dh in dhResults)
                {
                    CryptoHelpers.SecureClear(dh);
                }
                CryptoHelpers.SecureClear(ephemeralPrivateKey);

                return CryptoResult<X3DHResult>.Success(new X3DHResult(
                    sharedSecretResult.Value,
                    associatedData,
                    ephemeralPublicKey,
                    usedOneTimePreKeyId));
            }
            catch (Exception ex)
            {
                return CryptoResult<X3DHResult>.Failure($"X3DH initiator agreement failed: {ex.Message}");
            }
        }

        /// <inheritdoc/>
        public CryptoResult<X3DHResult> ResponderAgree(
            AsymmetricKeyPair recipientIdentityKeyPair,
            AsymmetricKeyPair recipientSignedPreKeyPair,
            AsymmetricKeyPair? recipientOneTimePreKeyPair,
            byte[] senderIdentityPublicKey,
            byte[] senderEphemeralPublicKey)
        {
            ThrowIfDisposed();

            if (recipientIdentityKeyPair == null)
            {
                return CryptoResult<X3DHResult>.Failure("Recipient identity key pair cannot be null.");
            }

            if (recipientSignedPreKeyPair == null)
            {
                return CryptoResult<X3DHResult>.Failure("Recipient signed pre-key pair cannot be null.");
            }

            if (senderIdentityPublicKey == null)
            {
                return CryptoResult<X3DHResult>.Failure("Sender identity public key cannot be null.");
            }

            if (senderEphemeralPublicKey == null)
            {
                return CryptoResult<X3DHResult>.Failure("Sender ephemeral public key cannot be null.");
            }

            try
            {
                // Perform the DH computations (mirror of initiator)
                List<byte[]> dhResults = new();

                // DH1: Recipient Signed Pre-Key (private) + Sender Identity (public)
                CryptoResult<byte[]> dh1 = PerformDH(recipientSignedPreKeyPair.PrivateKey, senderIdentityPublicKey);
                if (dh1.IsFailure)
                {
                    return CryptoResult<X3DHResult>.Failure($"DH1 failed: {dh1.Error}");
                }
                dhResults.Add(dh1.Value);

                // DH2: Recipient Identity (private) + Sender Ephemeral (public)
                CryptoResult<byte[]> dh2 = PerformDH(recipientIdentityKeyPair.PrivateKey, senderEphemeralPublicKey);
                if (dh2.IsFailure)
                {
                    return CryptoResult<X3DHResult>.Failure($"DH2 failed: {dh2.Error}");
                }
                dhResults.Add(dh2.Value);

                // DH3: Recipient Signed Pre-Key (private) + Sender Ephemeral (public)
                CryptoResult<byte[]> dh3 = PerformDH(recipientSignedPreKeyPair.PrivateKey, senderEphemeralPublicKey);
                if (dh3.IsFailure)
                {
                    return CryptoResult<X3DHResult>.Failure($"DH3 failed: {dh3.Error}");
                }
                dhResults.Add(dh3.Value);

                // DH4: Recipient One-Time Pre-Key (private) + Sender Ephemeral (public) - optional
                int? usedOneTimePreKeyId = null;
                if (recipientOneTimePreKeyPair != null)
                {
                    CryptoResult<byte[]> dh4 = PerformDH(recipientOneTimePreKeyPair.PrivateKey, senderEphemeralPublicKey);
                    if (dh4.IsFailure)
                    {
                        return CryptoResult<X3DHResult>.Failure($"DH4 failed: {dh4.Error}");
                    }
                    dhResults.Add(dh4.Value);
                    // Note: The one-time pre-key ID should be provided separately
                }

                // Concatenate all DH outputs
                byte[] dhConcat = ConcatenateArrays(dhResults.ToArray());

                // Derive the shared secret using HKDF
                CryptoResult<byte[]> sharedSecretResult = _hkdf.DeriveKey(dhConcat, null, X3DHInfo, 32);
                if (sharedSecretResult.IsFailure)
                {
                    return CryptoResult<X3DHResult>.Failure($"Key derivation failed: {sharedSecretResult.Error}");
                }

                // Create associated data (AD = Encode(IK_A) || Encode(IK_B))
                byte[] associatedData = ConcatenateArrays(
                    senderIdentityPublicKey,
                    recipientIdentityKeyPair.PublicKey);

                // Clear sensitive data
                CryptoHelpers.SecureClear(dhConcat);
                foreach (byte[] dh in dhResults)
                {
                    CryptoHelpers.SecureClear(dh);
                }

                return CryptoResult<X3DHResult>.Success(new X3DHResult(
                    sharedSecretResult.Value,
                    associatedData,
                    null, // Responder doesn't have ephemeral public key to return
                    usedOneTimePreKeyId));
            }
            catch (Exception ex)
            {
                return CryptoResult<X3DHResult>.Failure($"X3DH responder agreement failed: {ex.Message}");
            }
        }

        /// <inheritdoc/>
        public CryptoResult<PreKeyBundleWithPrivateKeys> GeneratePreKeyBundle(
            AsymmetricKeyPair identityKeyPair,
            int signedPreKeyId,
            int[]? oneTimePreKeyIds = null)
        {
            ThrowIfDisposed();

            if (identityKeyPair == null)
            {
                return CryptoResult<PreKeyBundleWithPrivateKeys>.Failure("Identity key pair cannot be null.");
            }

            try
            {
                // Generate signed pre-key
                using EcdhKeyExchange signedPreKeyEcdh = new(_curve);
                CryptoResult<AsymmetricKeyPair> signedPreKeyResult = signedPreKeyEcdh.GenerateKeyPair();
                if (signedPreKeyResult.IsFailure)
                {
                    return CryptoResult<PreKeyBundleWithPrivateKeys>.Failure(
                        $"Failed to generate signed pre-key: {signedPreKeyResult.Error}");
                }

                // Sign the signed pre-key with identity key
                CryptoResult<byte[]> signatureResult = SignPreKey(
                    identityKeyPair.PrivateKey,
                    signedPreKeyResult.Value.PublicKey);
                if (signatureResult.IsFailure)
                {
                    return CryptoResult<PreKeyBundleWithPrivateKeys>.Failure(
                        $"Failed to sign pre-key: {signatureResult.Error}");
                }

                // Generate one-time pre-keys if requested
                Dictionary<int, byte[]> oneTimePreKeyPrivates = new();
                byte[]? firstOneTimePreKey = null;
                int? firstOneTimePreKeyId = null;

                if (oneTimePreKeyIds != null && oneTimePreKeyIds.Length > 0)
                {
                    foreach (int id in oneTimePreKeyIds)
                    {
                        using EcdhKeyExchange otpkEcdh = new(_curve);
                        CryptoResult<AsymmetricKeyPair> otpkResult = otpkEcdh.GenerateKeyPair();
                        if (otpkResult.IsFailure)
                        {
                            continue; // Skip failed generations
                        }

                        oneTimePreKeyPrivates[id] = otpkResult.Value.PrivateKey;

                        // Store the first one for the bundle
                        if (firstOneTimePreKey == null)
                        {
                            firstOneTimePreKey = otpkResult.Value.PublicKey;
                            firstOneTimePreKeyId = id;
                        }
                    }
                }

                PreKeyBundle bundle = new(
                    identityKeyPair.PublicKey,
                    signedPreKeyResult.Value.PublicKey,
                    signatureResult.Value,
                    signedPreKeyId,
                    firstOneTimePreKey,
                    firstOneTimePreKeyId);

                PreKeyBundleWithPrivateKeys result = new(
                    bundle,
                    signedPreKeyResult.Value.PrivateKey,
                    oneTimePreKeyPrivates);

                return CryptoResult<PreKeyBundleWithPrivateKeys>.Success(result);
            }
            catch (Exception ex)
            {
                return CryptoResult<PreKeyBundleWithPrivateKeys>.Failure(
                    $"Failed to generate pre-key bundle: {ex.Message}");
            }
        }

        /// <summary>
        /// Performs a Diffie-Hellman key agreement operation.
        /// </summary>
        private CryptoResult<byte[]> PerformDH(byte[] privateKey, byte[] publicKey)
        {
            try
            {
                using ECDiffieHellman ecdh = ECDiffieHellman.Create();
                ecdh.ImportPkcs8PrivateKey(privateKey, out _);

                using ECDiffieHellman remoteEcdh = ECDiffieHellman.Create();
                remoteEcdh.ImportSubjectPublicKeyInfo(publicKey, out _);

                byte[] sharedSecret = ecdh.DeriveKeyMaterial(remoteEcdh.PublicKey);
                return CryptoResult<byte[]>.Success(sharedSecret);
            }
            catch (Exception ex)
            {
                return CryptoResult<byte[]>.Failure($"DH operation failed: {ex.Message}");
            }
        }

        /// <summary>
        /// Signs a pre-key using the identity private key.
        /// </summary>
        private CryptoResult<byte[]> SignPreKey(byte[] identityPrivateKey, byte[] preKey)
        {
            try
            {
                using ECDsa ecdsa = ECDsa.Create();
                ecdsa.ImportPkcs8PrivateKey(identityPrivateKey, out _);
                byte[] signature = ecdsa.SignData(preKey, HashAlgorithmName.SHA256);
                return CryptoResult<byte[]>.Success(signature);
            }
            catch (Exception ex)
            {
                return CryptoResult<byte[]>.Failure($"Signing failed: {ex.Message}");
            }
        }

        /// <summary>
        /// Verifies a signed pre-key signature.
        /// </summary>
        private CryptoResult<bool> VerifySignedPreKey(byte[] identityPublicKey, byte[] preKey, byte[] signature)
        {
            try
            {
                using ECDsa ecdsa = ECDsa.Create();
                ecdsa.ImportSubjectPublicKeyInfo(identityPublicKey, out _);
                bool isValid = ecdsa.VerifyData(preKey, signature, HashAlgorithmName.SHA256);
                return CryptoResult<bool>.Success(isValid);
            }
            catch (Exception ex)
            {
                return CryptoResult<bool>.Failure($"Verification failed: {ex.Message}");
            }
        }

        /// <summary>
        /// Concatenates multiple byte arrays.
        /// </summary>
        private static byte[] ConcatenateArrays(params byte[][] arrays)
        {
            int totalLength = arrays.Sum(a => a.Length);
            byte[] result = new byte[totalLength];
            int offset = 0;

            foreach (byte[] array in arrays)
            {
                Buffer.BlockCopy(array, 0, result, offset, array.Length);
                offset += array.Length;
            }

            return result;
        }

        /// <summary>
        /// Gets the curve name for display purposes.
        /// </summary>
        private static string GetCurveName(ECCurve curve)
        {
            if (curve.Oid?.FriendlyName != null)
            {
                return curve.Oid.FriendlyName;
            }

            return "Unknown";
        }

        /// <summary>
        /// Throws an <see cref="ObjectDisposedException"/> if this instance has been disposed.
        /// </summary>
        private void ThrowIfDisposed()
        {
            if (_disposed)
            {
                throw new ObjectDisposedException(nameof(X3DHKeyAgreement));
            }
        }

        /// <inheritdoc/>
        public void Dispose()
        {
            if (!_disposed)
            {
                _hkdf.Dispose();
                _disposed = true;
            }
        }
    }
}
#endif
